-- Corrige mensagem_familia dos protocolos que ficaram com o texto genérico de
-- demonstração (copiado do seed em 016) em vez de uma mensagem própria do protocolo.
-- Só atualiza linhas que ainda estão com o texto genérico original: edições feitas
-- manualmente pelo Admin do Assistente Fadelito depois do seed não são sobrescritas.

BEGIN;

UPDATE public.protocolos
SET mensagem_familia = 'Olá, [nome do responsável]. Escrevemos sobre a administração de medicamento à criança na escola. A coordenação está conferindo a autorização e a documentação necessárias antes de qualquer procedimento, seguindo o protocolo da Rede Fadelito, e nenhuma medicação é administrada sem essa validação formal. Pedimos que envie ou confirme a receita e as orientações atualizadas pelo canal institucional. Qualquer dúvida, estamos à disposição para conversar.'
WHERE titulo = 'Protocolo de administração de medicamentos'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = 'Olá, [nome do responsável]. Precisamos informar que houve uma situação de emergência envolvendo a criança durante a rotina escolar. A equipe agiu imediatamente, prestou os primeiros cuidados e acionou a coordenação, seguindo o fluxo de emergência da unidade. Pedimos que entre em contato o quanto antes pelo canal institucional para alinharmos os próximos passos. Continuaremos acompanhando de perto e retornaremos com mais informações assim que possível.'
WHERE titulo = 'Protocolo de emergências'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = 'Olá, [nome do responsável]. Gostaríamos de compartilhar como está o processo de adaptação da criança à rotina escolar. A equipe tem acompanhado de perto os sinais de segurança e conforto, apresentando aos poucos os espaços, os educadores e o grupo. Vamos alinhar com você os próximos passos para que essa fase siga tranquila. Estamos à disposição para conversar sempre que precisar.'
WHERE titulo = 'Protocolo de adaptação'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = 'Olá, [nome do responsável]. Recebemos sua solicitação relacionada a imagens da criança. Estamos conferindo as autorizações e as regras de acesso antes de qualquer visualização, cópia ou entrega de material, conforme a política de privacidade da Rede Fadelito. Retornaremos pelo canal institucional assim que a verificação estiver concluída, sem antecipar prazos ou conteúdo antes dessa confirmação. Agradecemos a compreensão.'
WHERE titulo = 'Protocolo de fotos'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = ''
WHERE titulo = 'Protocolo de uso do parque'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = 'Olá, [nome do responsável]. Notamos algumas ausências da criança nos últimos dias e gostaríamos de entender como podemos ajudar. Se houver alguma dificuldade de rotina, saúde ou adaptação, estamos à disposição para conversar e buscar juntos uma solução. Seu retorno nos ajuda a manter o acompanhamento pedagógico em dia.'
WHERE titulo = 'Protocolo de alunos faltantes'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = 'Olá, [nome do responsável]. Precisamos conversar sobre uma situação reportada envolvendo a criança. A equipe acolheu o relato, registrou os fatos com cuidado e encaminhou o caso à direção para apuração formal, sem antecipar conclusões. Por se tratar de um tema de proteção infantil, seguiremos o fluxo institucional e retornaremos com informações assim que a apuração permitir. Permanecemos à disposição para dialogar diretamente com você.'
WHERE titulo = 'Protocolo de crise e conduta inadequada'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = 'Olá, [nome do responsável]. Foi um prazer receber sua visita à unidade. Registramos suas dúvidas e o que foi combinado durante o atendimento, e retornaremos pelo canal institucional dentro do prazo combinado. Se surgir alguma pergunta antes disso, estamos à disposição para ajudar.'
WHERE titulo = 'Protocolo de visita e pós-visita'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = ''
WHERE titulo = 'Protocolo de postura'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = ''
WHERE titulo = 'Protocolo lista de alunos e capacidade'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = ''
WHERE titulo = 'Protocolo de planejamento'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = 'Olá, [nome do responsável]. Gostaríamos de conversar sobre observações feitas durante o acompanhamento pedagógico da criança. Nossa equipe registra evidências ao longo da rotina para entender avanços e necessidades, sempre em conjunto com a coordenação, sem rótulos ou comparações. Queremos alinhar com você as estratégias que podem apoiar o desenvolvimento nesta fase. Ficamos à disposição para marcar uma conversa.'
WHERE titulo = 'Protocolo de avaliação diagnóstica'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = 'Olá, [nome do responsável]. Compartilhamos as informações do dia do bebê na escola: alimentação, sono, trocas e observações da rotina, registradas pela equipe do berçário. Qualquer sinal de mal-estar é comunicado imediatamente à coordenação e, quando necessário, a você. Estamos à disposição pelo canal institucional para qualquer dúvida sobre os cuidados.'
WHERE titulo = 'Protocolo da rotina do berçário'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = ''
WHERE titulo = 'Protocolo de cumprimento de rotina'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = 'Olá, [nome do responsável]. Segue o registro do dia da criança na escola, com as informações necessárias sobre a rotina. Qualquer ocorrência mais sensível é conversada primeiro com a coordenação antes de chegar até você, e assuntos de saúde seguem sempre o fluxo formal validado. Estamos à disposição pelo canal institucional para esclarecer qualquer ponto da agenda.'
WHERE titulo = 'Protocolo de agenda'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = 'Olá, [nome do responsável]. Segue o relatório de desenvolvimento da criança referente ao período, já revisado pela coordenação. Nele você encontra avanços, desafios observados e os próximos objetivos pedagógicos, sem rótulos ou comparações com outras crianças. Estamos à disposição para conversar sobre qualquer ponto do relatório.'
WHERE titulo = 'Protocolo de relatórios'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = 'Olá, [nome do responsável]. Gostaríamos de compartilhar os objetivos pedagógicos definidos para a turma da criança nesta etapa. Eles orientam o planejamento e as experiências propostas no dia a dia, considerando o ritmo do grupo e as necessidades individuais, sem promessas de resultados padronizados. Estamos à disposição para conversar sobre o desenvolvimento da criança.'
WHERE titulo = 'Protocolo dos objetivos das turmas'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = 'Olá, [nome do responsável]. Gostaríamos de compartilhar como está o processo de alfabetização da criança, com base nas evidências pedagógicas observadas pela equipe. As propostas respeitam o ritmo individual, sem comparações ou constrangimento, e são ajustadas com a coordenação sempre que necessário. Ficamos à disposição para conversar sobre o método e a evolução até aqui.'
WHERE titulo = 'Protocolo de alfabetização'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = 'Olá, [nome do responsável]. Gostaríamos de compartilhar como o bebê tem respondido às propostas do programa Baby Learning nesta etapa. A equipe conduz as atividades com supervisão próxima, respeitando os sinais individuais e interrompendo qualquer proposta diante de desconforto. Os resultados observados são compartilhados com a coordenação antes de qualquer ajuste na continuidade. Estamos à disposição para conversar sobre o desenvolvimento do bebê no programa.'
WHERE titulo = 'Protocolo Baby Learning'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = ''
WHERE titulo = 'Protocolo de férias da Rede Fadelito'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = 'Olá, [nome do responsável]. Gostaríamos de conversar sobre a transição da criança para o minimaternal. A coordenação já avaliou os sinais de prontidão e vamos planejar juntos uma aproximação gradual ao novo ambiente, aos novos educadores e à nova rotina. Acompanharemos de perto os primeiros dias e ajustaremos o ritmo conforme a necessidade da criança. Estamos à disposição para alinhar os próximos passos com você.'
WHERE titulo = 'Protocolo de transição para o minimaternal'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = 'Olá, [nome do responsável]. Recebemos sua manifestação e queremos entender melhor como podemos ajudar. Registramos a demanda e já definimos um responsável e um prazo para retornarmos com uma solução pelo canal institucional. Sua satisfação é importante para nós e vamos acompanhar o combinado até a conclusão.'
WHERE titulo = 'Protocolo de manutenção de aluno'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = ''
WHERE titulo = 'Protocolo de faltas e atrasos da equipe'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = 'Olá, [nome do responsável]. Vamos combinar os detalhes da comemoração de aniversário da criança na escola: data, formato permitido e restrições da unidade. Pedimos que confirme alergias e regras alimentares antes do envio de qualquer item, e lembramos que a exposição de imagens segue apenas as autorizações já registradas. Ficamos à disposição para alinhar horário e espaço com você.'
WHERE titulo = 'Protocolo de festa de aniversário'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = 'Olá, [nome do responsável]. Ao organizar a mochila da criança, identificamos uma pendência de item, troca ou reposição para a rotina. Pedimos a gentileza de conferir e providenciar o necessário antes da próxima aula. Qualquer dúvida sobre o que falta, estamos à disposição pelo canal institucional.'
WHERE titulo = 'Protocolo de organização da mochila'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = ''
WHERE titulo = 'Protocolo para escovação'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = ''
WHERE titulo = 'Protocolo de reunião pedagógica'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = ''
WHERE titulo = 'Protocolo de webinar'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = ''
WHERE titulo = 'Protocolo de prevenção contra Covid-19'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = ''
WHERE titulo = 'Planejamento pedagógico — estrutura detalhada'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = ''
WHERE titulo = 'Protocolo de rematrícula — fonte inconsistente'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = ''
WHERE titulo = 'Protocolo de treinamento Engage Pedagógico'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = ''
WHERE titulo = 'Protocolo de contratação'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = ''
WHERE titulo = 'Protocolo de almoço Colaborador Mais'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = ''
WHERE titulo = 'Protocolo de lago e aquário'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = ''
WHERE titulo = 'Protocolo de relógio de ponto'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = ''
WHERE titulo = 'Protocolo do jantar Melhor Escola do Mês'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = ''
WHERE titulo = 'Protocolo de manutenção predial'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = ''
WHERE titulo = 'Protocolo de rescisão de estágio'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

UPDATE public.protocolos
SET mensagem_familia = ''
WHERE titulo = 'Pais aniversariantes — fonte inconsistente'
  AND mensagem_familia IN ('Olá, [nome do responsável]. Gostaríamos de conversar sobre uma situação observada na rotina escolar. A equipe acolheu a criança, registrou os fatos objetivos e encaminhou o tema à coordenação. Estamos seguindo o protocolo da Rede Fadelito e retornaremos pelo canal institucional com os próximos passos. Permanecemos à disposição para dialogar.', 'Olá, [nome do responsável]. Estamos entrando em contato para informar uma situação relacionada a registros de imagem. Assim que o tema foi identificado, preservamos as informações e encaminhamos a verificação à direção, seguindo as regras de privacidade e acesso da escola. Estamos confirmando os fatos antes de qualquer conclusão e retornaremos pelo canal institucional com o posicionamento e os próximos passos. Ficamos à disposição para conversar.');

COMMIT;
