-- Importa a lista de alunos da unidade Anália Franco (planilha "Alunos Anália
-- Franco.xlsx") para a rematrícula, evitando digitação manual um a um.
-- Não insere duplicados: roda sempre por cima do estado atual da tabela.

INSERT INTO public.rematricula_alunos (unidade_id, nome, turma)
SELECT p.id, v.nome, v.turma
FROM public.profiles p
CROSS JOIN (VALUES
  ('AISHA ASSAD SANDOVAL', 'EI - Mat. II'),
  ('ALICE BATISTA LEITE', 'EI - Berçário'),
  ('ALICE YUN PASQUETO CHANG', 'EI - Jardim'),
  ('ANNA JULIA JIAXIN LEE', 'EI - Mat. II'),
  ('ANTONELA BATALHA', 'EI - Berçário'),
  ('ANTONELLA COSTABILE FERNADES', 'EI - Berçário'),
  ('ARTHUR RUFINO FURLANETTO', 'EI - Mat. II'),
  ('BELLA NASCIMENTO ALBIERI', 'EI - Jardim'),
  ('CAROLINA GALDINO ARRUDA', 'EI - Mat. II'),
  ('CECILIA DO NASCIMENTO MENDES CAMARGO', 'EI - Mat. II'),
  ('CECILIA ELEUTERIO GARCIA GAZOTE', 'EI - Mat. I'),
  ('CECILIA NERES CAMINSKI', 'EI - Jardim'),
  ('DANIEL BARBOSA DE MEDEIROS LIMA', 'EI - Mini'),
  ('DANIEL GUIMARÃES MENA', 'EI - Mat. I'),
  ('DANTE VENTURA PAGANI', 'EI - Mat. I'),
  ('DAVI DE SOUZA MARINHO', 'EI - Mat. I'),
  ('DAVI PAIOLA DESIDERIO', 'EI - Mini'),
  ('DIMITRI PASSATUTO FALOPA', 'EI - Mini'),
  ('EVA RODRIGUES DOS SANTOS', 'EI - Berçário'),
  ('FERNANDA MARGIUNTI COSTA', 'EI - Mat. II'),
  ('FRANCISCO BAIOCHI VERDELLI', 'EI - Mat. II'),
  ('GABRIEL IZZO REIMÃO MARIN JACOB', 'EI - Jardim'),
  ('GABRIEL LARANGEIRA REIS SANTANA', 'EI - Mat. II'),
  ('GABRIEL VINCENZO JESUS SILVA', 'EI - Mat. I'),
  ('GUILHERME TAMAM DOS SANTOS', 'EI - Jardim'),
  ('HELENA MARIA SARAIVA SERRA', 'EI - Mat. I'),
  ('HENRIQUE FARIAS ALVES', 'EI - Jardim'),
  ('IAN PASSATUTO FALOPA', 'EI - Mini'),
  ('ISABEL SILVA BOSCACHE AYACHE', 'EI - Mini'),
  ('ISIS TRINDADE MOTTA', 'EI - Mat. II'),
  ('JOÃO MIGUEL DOS SANTOS KLAIN', 'EI - Mat. I'),
  ('JOÃO PEDRO MARQUES GIMENES', 'EI - Berçário'),
  ('JULIO GALDINO ARRUDA', 'EI - Jardim'),
  ('KALEL IKUNO SANTANA', 'EI - Berçário'),
  ('LARISSA DANIELA BLANCO INGALA', 'EI - Jardim'),
  ('LAURA FREIRE ZANELLI', 'EI - Jardim'),
  ('LAURA MANTIC CORREIA GONZALEZ', 'EI - Mat. II'),
  ('LEONARDO BENJAMIN JESUS SILVA', 'EI - Mat. I'),
  ('LEONARDO MARABA DE LIMA', 'EI - Mat. I'),
  ('LIVIA OLIVEIRA CARDOSO', 'EI - Mini'),
  ('LUCAS BENAZZATO MONTEIRO', 'EI - Berçário'),
  ('LUCAS BRACHINI LUIS', 'EI - Berçário'),
  ('LUÍSA BERNARDES LORETE CHAVES', 'EI - Berçário'),
  ('LUIZA SANTANA DOS ANJOS', 'EI - Mat. II'),
  ('MAITÊ DO VALLE MURAD', 'EI - Mat. I'),
  ('MANUEL ZAMPOLI RAMINELLI VILELA', 'EI - Mat. I'),
  ('MANUELA MARQUES GIMENES', 'EI - Mat. I'),
  ('MANUELLA ALPENDRE ZECHINATO', 'EI - Mat. I'),
  ('MANUELLA APARECIDA OLIVEIRA SANTANA', 'EI - Mat. I'),
  ('MARCUS VINICIUS PEREIRA DA SILVA NETO', 'EI - Mat. I'),
  ('MARIA LUIZA MAGALHÃES DE LIMA', 'EI - Berçário'),
  ('MARIAH VENTURA PAGANI', 'EI - Berçário'),
  ('MATEO HUARAHUARA MAMANI', 'EI - Mat. II'),
  ('MATTEO GUIMARAES BRUNELLI', 'EI - Mat. I'),
  ('MAXIMILIANO REYES AIZA', 'EI - Mini'),
  ('MIA BABILÔNIA DE GIACCO', 'EI - Mini'),
  ('MIGUEL MONTENEGRO ARAUJO VIDAL', 'EI - Mini'),
  ('MIGUEL RAMOS BENTO', 'EI - Mat. I'),
  ('MIGUEL SILVA NAKAO', 'EI - Mat. II'),
  ('MURILLO COLE BATOCHIO ROSA', 'EI - Mini'),
  ('NOAH FOGAÇA COSTA', 'EI - Jardim'),
  ('PEDRO BARBOSA DE MEDEIROS LIMA FILHO', 'EI - Jardim'),
  ('PEDRO SILVA SILVA', 'EI - Mini'),
  ('PIETRA LIMA GOMES', 'EI - Mat. I'),
  ('RAFAEL STEFANUTO RODRIGUES SILVA', 'EI - Mat. I'),
  ('RAVENA CASSARÁ BOTELHO', 'EI - Berçário'),
  ('REBECA ANDRADE DE BRITO', 'EI - Mat. II'),
  ('REBECA CASSARÁ BOTELHO', 'EI - Mat. II'),
  ('ROMEU ALVES SINOTT CAMARGO', 'EI - Mat. I'),
  ('THEO VIEIRA VAZ GATO', 'EI - Jardim'),
  ('THEODORO ZANELLATO', 'EI - Mat. II'),
  ('THOMAS KANAAN ASSUNÇÃO', 'EI - Mini'),
  ('VICENTE CATALDI', 'EI - Berçário'),
  ('VIVIAN HIKARI HIGA ALMEIDA', 'EI - Berçário'),
  ('YVO RENATO BATISTA RAMOS JUNIOR', 'EI - Mat. II'),
  ('ZOE MOURA PEDROSA', 'EI - Mini')
) AS v(nome, turma)
WHERE p.unidade_nome = 'Anália Franco'
  AND p.role = 'unidade'
  AND NOT EXISTS (
    SELECT 1 FROM public.rematricula_alunos r
    WHERE r.unidade_id = p.id AND r.nome = v.nome
  );
