-- Reintroduz Brooklin, Klabin, Perdizes e Real Parque (removidas em 5df0f84,
-- 2026-08-20) e semeia a lista de alunos da Rematrícula 2027 dessas 4 unidades
-- a partir das planilhas enviadas ("Painel- unidades Flávia/Moana").
-- Só insere depois que os 4 profiles existirem (ver supabase/seed-users-pendentes.js)
-- -- sem eles o JOIN por unidade_nome não acha ninguém e não insere nada, como
-- aconteceu com Aclimação (migration 029).
-- Klabin: coluna 'Unidade' da planilha original vinha como 'Chácara Klabin',
-- normalizado aqui pra 'Klabin' (nome canônico em UNIDADES).
-- Idempotente: NOT EXISTS evita duplicar se rodar de novo.

INSERT INTO public.rematricula_alunos (unidade_id, nome, turma)
SELECT p.id, v.nome, v.turma
FROM public.profiles p
JOIN (VALUES
  ('Brooklin', 'ARTHUR SILVA MAXIMO', 'EI - Mini'),
  ('Brooklin', 'ELOISA GRECHE LIBARDI', 'EI - Mini'),
  ('Brooklin', 'FLORA ABRAHAM DE ROSA', 'EI - Berçário'),
  ('Brooklin', 'GABRIEL MIZIARA FAUSTINI DA COSTA', 'EI - Berçário'),
  ('Brooklin', 'GIULIANA BRITO D''IPPOLITO', 'EI - Mini'),
  ('Brooklin', 'HEITOR BITENCOURT VON RONDOW', 'EI - Mini'),
  ('Brooklin', 'HELENA ALMEIDA BOTELHO', 'EI - Mini'),
  ('Brooklin', 'HENRIQUE LIMA PEREIRA DOS SANTOS', 'EI - Berçário'),
  ('Brooklin', 'LORENZO RODOLFO POLEGATO CASAGRANDE', 'EI - Berçário'),
  ('Brooklin', 'MANUELA RIBEIRO DE OLIVEIRA', 'EI - Mini'),
  ('Brooklin', 'MARIA EDUARDA CAMARGO GRILLO', 'EI - Berçário'),
  ('Brooklin', 'MIGUEL SANTOS MARIANO DA SILVA CURY', 'EI - Mini'),
  ('Brooklin', 'RAVI NOBRE SALES LARANJO', 'EI - Berçário'),
  ('Brooklin', 'ALICE FERREIRA FRIGE', 'EI - Pré'),
  ('Brooklin', 'BEATRIZ DE PIERI SALOMÃO', 'EI - Pré'),
  ('Brooklin', 'BRUNA DA PAZ BRAGA', 'EI - Pré'),
  ('Brooklin', 'DAVI TIUGANSI MORAES', 'EI - Pré'),
  ('Brooklin', 'GABRIEL PARO DE PAULA', 'EI - Pré'),
  ('Brooklin', 'GIOVANNI DE MEO TAVARES RAMOS', 'EI - Pré'),
  ('Brooklin', 'GUSTAVO FERREIRA SILVA', 'EI - Pré'),
  ('Brooklin', 'HELENA MERENDA FRANCISCHELLI', 'EI - Pré'),
  ('Brooklin', 'HELENA SOUZA POI', 'EI - Pré'),
  ('Brooklin', 'JOÃO SAPELLI ZOTTELE BOMFIM', 'EI - Pré'),
  ('Brooklin', 'JOAQUIM ARB DE GOES', 'EI - Pré'),
  ('Brooklin', 'LORENZO SALES MARTINAZZO', 'EI - Pré'),
  ('Brooklin', 'LUCAS MARTINS ROCHA', 'EI - Pré'),
  ('Brooklin', 'LUIZA DEL SOLE SPECK', 'EI - Pré'),
  ('Brooklin', 'MARCELA HEIMANN WITTE', 'EI - Pré'),
  ('Brooklin', 'MARIA EDUARDA PEREIRA CERQUEIRA', 'EI - Pré'),
  ('Brooklin', 'MARIA LUISA SOMMA GARLA', 'EI - Pré'),
  ('Brooklin', 'MARTIN POUSADA DOS SANTOS AVILA FERNANDES', 'EI - Pré'),
  ('Brooklin', 'MATTEO FERREIRA MENDES MESQUITA', 'EI - Pré'),
  ('Brooklin', 'MIGUEL NAGATA GÓES', 'EI - Pré'),
  ('Brooklin', 'PEDRO FLORA VIZENTIM', 'EI - Pré'),
  ('Brooklin', 'RAFAEL GOLIK NAKASHIMA', 'EI - Pré'),
  ('Brooklin', 'SOPHIA DE ALBUQUERQUE BOTECCHIA', 'EI - Pré'),
  ('Brooklin', 'THOMAZ SENRA FERREIRA', 'EI - Pré'),
  ('Brooklin', 'VICTORIA DI DONATO SAITA', 'EI - Pré'),
  ('Brooklin', 'VINCENZO TARTAROTTI MALTEZ', 'EI - Pré'),
  ('Brooklin', 'BENÍCIO PAGANI APRILE', 'EI - Mat. II'),
  ('Brooklin', 'BENÍCIO TOLEDO DE ABREU', 'EI - Mat. II'),
  ('Brooklin', 'BERNARDO NEVARES PACHECO', 'EI - Mat. II'),
  ('Brooklin', 'BERNARDO SOMMA GARLA', 'EI - Mat. II'),
  ('Brooklin', 'DANTE ANTONUCCI DE SÁ MORAES', 'EI - Mat. II'),
  ('Brooklin', 'DANTE BARBOSA SENA NETO', 'EI - Mat. II'),
  ('Brooklin', 'DANTE CORREA PARANAÍBA MATOS ARAÚJO', 'EI - Mat. II'),
  ('Brooklin', 'DONATELLA COLLA FRIAS', 'EI - Mat. II'),
  ('Brooklin', 'FERNANDO RACHID CHIUVITTO', 'EI - Mat. II'),
  ('Brooklin', 'GABRIEL COLTRE GOLMIA', 'EI - Mat. II'),
  ('Brooklin', 'GIOVANI ZANIBONI CAMANHO', 'EI - Mat. II'),
  ('Brooklin', 'JOÃO GUILHERME DOS RAMOS', 'EI - Mat. II'),
  ('Brooklin', 'LARA GUIMARÂES', 'EI - Mat. II'),
  ('Brooklin', 'LETÍCIA NERY PEREIRA', 'EI - Mat. II'),
  ('Brooklin', 'LUCCA FUZIHARA FORNAZARI', 'EI - Mat. II'),
  ('Brooklin', 'LUNA DE ANDRADE GALDINO', 'EI - Mat. II'),
  ('Brooklin', 'MATILDA CHIACCHIA OROSCO', 'EI - Mat. II'),
  ('Brooklin', 'MIGUEL MARTINS BARBOSA', 'EI - Mat. II'),
  ('Brooklin', 'OLÍVIA CAMARGO GRILLO', 'EI - Mat. II'),
  ('Brooklin', 'PEDRO PEDRINELLI CHAIM', 'EI - Mat. II'),
  ('Brooklin', 'SOFIA MILLER SIMÃO', 'EI - Mat. II'),
  ('Brooklin', 'VALENTINA WATANABE MATOS', 'EI - Mat. II'),
  ('Brooklin', 'ARTHUR ANGLADA FINATTO', 'EI - Jardim'),
  ('Brooklin', 'BENÍCIO GUIMARÃES AVELAR', 'EI - Jardim'),
  ('Brooklin', 'CAIQUE MADEIRA ARAGÃO', 'EI - Jardim'),
  ('Brooklin', 'DAVI MACHADO SINBO', 'EI - Jardim'),
  ('Brooklin', 'GIOVANNA PENTEADO GAMBARDELLA', 'EI - Jardim'),
  ('Brooklin', 'HEITOR RHODES MELO SILVA', 'EI - Jardim'),
  ('Brooklin', 'JOÃO PEDRO DA CUNHA SILVA', 'EI - Jardim'),
  ('Brooklin', 'JOÃO SEMEGHINI SANTANA', 'EI - Jardim'),
  ('Brooklin', 'JOAQUIM MASTELLI CAIRES', 'EI - Jardim'),
  ('Brooklin', 'JÚLIA MELO BISCOLA', 'EI - Jardim'),
  ('Brooklin', 'LAURA AIMI MIYAHARA ASUNAGA', 'EI - Jardim'),
  ('Brooklin', 'LAURA FERREIRA FRIGE', 'EI - Jardim'),
  ('Brooklin', 'LORENA ARENAS REIMBERG', 'EI - Jardim'),
  ('Brooklin', 'LORENA MENDES DOMINGUES', 'EI - Jardim'),
  ('Brooklin', 'LUCA TIBIRIÇÁ ALFEO REIS', 'EI - Jardim'),
  ('Brooklin', 'LUNA SCHAUBECK BURGATTI', 'EI - Jardim'),
  ('Brooklin', 'MARIA ALICE FERREIRA DAMIÃO GOMES', 'EI - Jardim'),
  ('Brooklin', 'MARIAH PLASTER PEREIRA PASSOS', 'EI - Jardim'),
  ('Brooklin', 'MATHEUS DA CUNHA GRIESI', 'EI - Jardim'),
  ('Brooklin', 'MURILO NASCIMENTO ALMEIDA', 'EI - Jardim'),
  ('Brooklin', 'PEDRO HENRIQUE MARTINS DE SÁ PIRES', 'EI - Jardim'),
  ('Brooklin', 'PIETRO CAMPAGNOLI DE VILHENA PEDACE', 'EI - Jardim'),
  ('Brooklin', 'RAFAELLA BOCCHIGLIERI FACCHETTI', 'EI - Jardim'),
  ('Brooklin', 'RAVI PERRELLA ARAUJO DE CAMARGO', 'EI - Jardim'),
  ('Brooklin', 'THÉO AMOROSO FACCIOLO', 'EI - Jardim'),
  ('Brooklin', 'THEO BARBOSA GUILHERME', 'EI - Jardim'),
  ('Brooklin', 'ALESSIA DI LUZIO HURTADO', 'EI - Mat. I'),
  ('Brooklin', 'ALICE SILVEIRA TELES', 'EI - Mat. I'),
  ('Brooklin', 'ARTUR AMAUCHI SONZA', 'EI - Mat. I'),
  ('Brooklin', 'BENJAMIN GUIMARÃES AVELAR', 'EI - Mat. I'),
  ('Brooklin', 'BENTO MORENO LEITE', 'EI - Mat. I'),
  ('Brooklin', 'JASMYN OLIVEIRA SILVA', 'EI - Mat. I'),
  ('Brooklin', 'LAURA SOUZA BONFIM', 'EI - Mat. I'),
  ('Brooklin', 'LÍVIA CARELO JUNQUEIRA PAIM', 'EI - Mat. I'),
  ('Brooklin', 'MAITÊ SILVEIRA CRUZ', 'EI - Mat. I'),
  ('Brooklin', 'THEO PISZGZMAN CUPERSMID VENCESLAU', 'EI - Mat. I'),
  ('Perdizes', 'ARTHUR SIBINELLI DINUCCI', 'EI - Mini'),
  ('Perdizes', 'EDUARDO ANDRADE BATISTA', 'EI - Mini'),
  ('Perdizes', 'ELOÍSA DE MENDONÇA SILVA', 'EI - Berçário'),
  ('Perdizes', 'EMANUEL BEZERRA EMILIANO', 'EI - Berçário'),
  ('Perdizes', 'HELENA MIZIARE LIMA', 'EI - Berçário'),
  ('Perdizes', 'JOAQUIM PATRIOTA DE LUCCAS CUSTÓDIO', 'EI - Berçário'),
  ('Perdizes', 'MATTEO CICCONI ZERBINATTI', 'EI - Mini'),
  ('Perdizes', 'NICOLAS FERNANDES ROSSETTI MIRANDA', 'EI - Mini'),
  ('Perdizes', 'PEDRO CEOLIN DE FARIA', 'EI - Berçário'),
  ('Perdizes', 'PEDRO SATORU SHIOTA FERRACINI', 'EI - Berçário'),
  ('Perdizes', 'RAFAEL FRANÇA FEITOSA', 'EI - Mini'),
  ('Perdizes', 'SARA KLEINE ROLAN', 'EI - Berçário'),
  ('Perdizes', 'SARA MOORI CUSTODIO', 'EI - Mini'),
  ('Perdizes', 'SOPHIA PINHEIRO FRESCA', 'EI - Berçário'),
  ('Perdizes', 'VALENTIM GOMES DE AGUIAR', 'EI - Mini'),
  ('Perdizes', 'AMELIE ALENCAR LEITE', 'EI - Pré'),
  ('Perdizes', 'BENICIO DANIELE RUIZ', 'EI - Pré'),
  ('Perdizes', 'BENÍCIO KOVACS MARCHI', 'EI - Pré'),
  ('Perdizes', 'BERNARDO CARDIM QUATTRONE', 'EI - Pré'),
  ('Perdizes', 'BERNARDO DELLAMANHA AMARAL', 'EI - Pré'),
  ('Perdizes', 'CRISTIANO AL ABDULLAH', 'EI - Pré'),
  ('Perdizes', 'DOM DAY ALMARAZ', 'EI - Pré'),
  ('Perdizes', 'EDAN YUXI PAN', 'EI - Pré'),
  ('Perdizes', 'ÉRICA ANDRADE DOS SANTOS LIMA', 'EI - Pré'),
  ('Perdizes', 'GABRIEL BUZZI HANCHUK', 'EI - Pré'),
  ('Perdizes', 'GUSTAVO UMETSU ROSATI', 'EI - Pré'),
  ('Perdizes', 'HENRIQUE BORGES LEE', 'EI - Pré'),
  ('Perdizes', 'ISABELA SILVA BERTONI', 'EI - Pré'),
  ('Perdizes', 'ISABELA VILANOVA GUIMARAES FONSECA', 'EI - Pré'),
  ('Perdizes', 'JOSÉ RAGUEB CHAHDA ANNIBAL', 'EI - Pré'),
  ('Perdizes', 'LAURA LA NOCE CÔRTES', 'EI - Pré'),
  ('Perdizes', 'LIZ LICHEWITZ LAPETINA', 'EI - Pré'),
  ('Perdizes', 'LUCAS DE ALMEIDA TALARICO', 'EI - Pré'),
  ('Perdizes', 'LUNA BARRETO MENEZES', 'EI - Pré'),
  ('Perdizes', 'MARCOS RAMOS FORMIGA', 'EI - Pré'),
  ('Perdizes', 'MARIA ALICE RAMALHO FELIX', 'EI - Pré'),
  ('Perdizes', 'MARIA CLARA DE SOUSA GIMENEZ', 'EI - Pré'),
  ('Perdizes', 'MARIA EDUARDA LUIZ LOBITSKY', 'EI - Pré'),
  ('Perdizes', 'MARIA HELENA BARRENSE CRISTOVÃO', 'EI - Pré'),
  ('Perdizes', 'MAYA KOCH DUTRA NUNES', 'EI - Pré'),
  ('Perdizes', 'MELINA ALENCAR LEITE', 'EI - Pré'),
  ('Perdizes', 'MIGUEL SALE PEZZUTTI', 'EI - Pré'),
  ('Perdizes', 'NICOLAS MARINHO MOREIRA RAMOS ZIETLOW', 'EI - Pré'),
  ('Perdizes', 'NICOLE BUCCINI BISCUOLA', 'EI - Pré'),
  ('Perdizes', 'NOAH BELLO MARIN', 'EI - Pré'),
  ('Perdizes', 'NOAH STEHLING CORDEIRO', 'EI - Pré'),
  ('Perdizes', 'PIETRO GAZEBAYOUKIAN BALVEDI', 'EI - Pré'),
  ('Perdizes', 'SOFIA ALBUQUERQUE JAU', 'EI - Pré'),
  ('Perdizes', 'THÉO CORREIA DE OLIVEIRA', 'EI - Pré'),
  ('Perdizes', 'THÉO EGAS GAROFALO', 'EI - Pré'),
  ('Perdizes', 'THÉO PASCHOAL VIEIRA', 'EI - Pré'),
  ('Perdizes', 'THEO SEIXAS ROTTER', 'EI - Pré'),
  ('Perdizes', 'ALICE SFREDDO GRABARZ', 'EI - Mat. II'),
  ('Perdizes', 'ANA CAROLINA GIBELLI XAVIER SABBAG CAIAFA', 'EI - Mat. II'),
  ('Perdizes', 'ANNA MAREUSE KOJIN', 'EI - Mat. II'),
  ('Perdizes', 'ARTHUR OLIVEIRA LAPETINA', 'EI - Mat. II'),
  ('Perdizes', 'BIANCA GIUNTINI RISTUM', 'EI - Mat. II'),
  ('Perdizes', 'BRENO MORILLA REIS', 'EI - Mat. II'),
  ('Perdizes', 'CAROLINA LAMOUNIER DE MOURA NABARRO', 'EI - Mat. II'),
  ('Perdizes', 'CLARICE CALIMERA SARDINI', 'EI - Mat. II'),
  ('Perdizes', 'EDUARDO FRANÇA FEITOSA', 'EI - Mat. II'),
  ('Perdizes', 'FELIPE GONÇALVES STANGALIN', 'EI - Mat. II'),
  ('Perdizes', 'GABRIEL AL ABDULLAH', 'EI - Mat. II'),
  ('Perdizes', 'GABRIELA MEI LUCCAS IDE', 'EI - Mat. II'),
  ('Perdizes', 'GUILHERME CASTELLANO VICENTE', 'EI - Mat. II'),
  ('Perdizes', 'HEITOR CASPARY SILVEIRA NOVAES DA SILVA', 'EI - Mat. II'),
  ('Perdizes', 'JOÃO GUILHERME DE ALMEIDA ALVES', 'EI - Mat. II'),
  ('Perdizes', 'JOÃO MACIEJEWSKI SALVAGNO', 'EI - Mat. II'),
  ('Perdizes', 'João Pedro Mazzotti Proença', 'EI - Mat. II'),
  ('Perdizes', 'JORGE GERÔNIMO DE SAUTI FERREIRA', 'EI - Mat. II'),
  ('Perdizes', 'JULIA LIMA CAFASSO', 'EI - Mat. II'),
  ('Perdizes', 'LUCA ROSA ZUCCO', 'EI - Mat. II'),
  ('Perdizes', 'LUCCA FURLAN MANCUSI', 'EI - Mat. II'),
  ('Perdizes', 'MARIA ELISA MARTINEZ GARBIN', 'EI - Mat. II'),
  ('Perdizes', 'MATHEUS CONDE TRIVELLI', 'EI - Mat. II'),
  ('Perdizes', 'MAURÍCIO ANTÔNIO MICALI OTTONI SILVA', 'EI - Mat. II'),
  ('Perdizes', 'MICAELA STIPP MORGENSZTERN', 'EI - Mat. II'),
  ('Perdizes', 'NICOLAS FISCHEL MATEO', 'EI - Mat. II'),
  ('Perdizes', 'RAFAEL LEME ARNIZANT', 'EI - Mat. II'),
  ('Perdizes', 'RAFAEL PELOSO TÁPIAS', 'EI - Mat. II'),
  ('Perdizes', 'TOMAS FERRO ZANINI', 'EI - Mat. II'),
  ('Perdizes', 'VICENTE ABRIATTA VALÉRIO', 'EI - Mat. II'),
  ('Perdizes', 'VICTOR ANTONIO METSIK ROMEO CANELA', 'EI - Mat. II'),
  ('Perdizes', 'ÁLVARO DE OLIVEIRA ANTONINI DOS SANTOS', 'EI - Jardim'),
  ('Perdizes', 'ANA BEATRIZ MANZI GOZZI', 'EI - Jardim'),
  ('Perdizes', 'ARTHUR AGUIAR MACHADO DE OLIVEIRA', 'EI - Jardim'),
  ('Perdizes', 'ARTHUR DAU CAMARGO TURCO', 'EI - Jardim'),
  ('Perdizes', 'CAROLINA ARAÚJO SALDYS', 'EI - Jardim'),
  ('Perdizes', 'CECILIA DIAS GINAK', 'EI - Jardim'),
  ('Perdizes', 'CLARA CARDOSO MEDEIROS DE CASTRO', 'EI - Jardim'),
  ('Perdizes', 'EDUARDO MEIRELLES GUZMAN', 'EI - Jardim'),
  ('Perdizes', 'FILIPPO DE OLIVEIRA ANTONINI DOS SANTOS', 'EI - Jardim'),
  ('Perdizes', 'GABRIELA DE MARI BARBOSA DE JESUS', 'EI - Jardim'),
  ('Perdizes', 'GUSTAVO JUNQUEIRA FRANCO VEIGA', 'EI - Jardim'),
  ('Perdizes', 'GUSTAVO LEVAY ARMANI', 'EI - Jardim'),
  ('Perdizes', 'JOSÉ MILHEM CHALITA BISNETO', 'EI - Jardim'),
  ('Perdizes', 'LAVÍNIA (WANYU ZHU)', 'EI - Jardim'),
  ('Perdizes', 'LEONARDO MARTINS DENADAI', 'EI - Jardim'),
  ('Perdizes', 'Lucas Monsanto Colombo', 'EI - Jardim'),
  ('Perdizes', 'LUCCA REBOUÇAS MAYER', 'EI - Jardim'),
  ('Perdizes', 'LUISA TOZZI FAGNANI', 'EI - Jardim'),
  ('Perdizes', 'MANUELA LIPPE GOBBO', 'EI - Jardim'),
  ('Perdizes', 'MATHEUS LEON ABDUCH', 'EI - Jardim'),
  ('Perdizes', 'MAX ALBINO RICCI', 'EI - Jardim'),
  ('Perdizes', 'MAYA CALDEIRA ORLANDO', 'EI - Jardim'),
  ('Perdizes', 'MELINA FAGUNDES CAVALCANTI', 'EI - Jardim'),
  ('Perdizes', 'MIAH UNHEIZER ASSEF NUNES', 'EI - Jardim'),
  ('Perdizes', 'MIGUEL SOUZA VITORIA', 'EI - Jardim'),
  ('Perdizes', 'MIRELLA MANZALLI MARTINELLI', 'EI - Jardim'),
  ('Perdizes', 'NARA CALHADO CORTEZ', 'EI - Jardim'),
  ('Perdizes', 'NUNO GIMENEZ RAIMUNDO DA COSTA', 'EI - Jardim'),
  ('Perdizes', 'OLÍVIA MACHADO BITTENCOURT', 'EI - Jardim'),
  ('Perdizes', 'OLÍVIA SEISCENTOS MARANO', 'EI - Jardim'),
  ('Perdizes', 'PEDRO TROLEGI VOSO', 'EI - Jardim'),
  ('Perdizes', 'RAVI FERRARO BÖHME', 'EI - Jardim'),
  ('Perdizes', 'ROMEO LOURENÇO CASMALLA', 'EI - Jardim'),
  ('Perdizes', 'VICENTE FERNANDES ROSSETTI MIRANDA', 'EI - Jardim'),
  ('Perdizes', 'VICENTE LAMOUNIER DE MOURA NABARRO', 'EI - Jardim'),
  ('Perdizes', 'ANA CECÍLIA DIAS LEME', 'EI - Mat. I'),
  ('Perdizes', 'AURORA SOUZA COSTELLA', 'EI - Mat. I'),
  ('Perdizes', 'BEATRIZ BERGAUER DINIZ', 'EI - Mat. I'),
  ('Perdizes', 'CATARINA GOTSIS MALUF', 'EI - Mat. I'),
  ('Perdizes', 'CLARA RODRIGUES WAIDEMAN', 'EI - Mat. I'),
  ('Perdizes', 'FELIPE SILVEIRA DE LUCA', 'EI - Mini'),
  ('Perdizes', 'FILIPPO SIQUEIRA PRONI', 'EI - Mat. I'),
  ('Perdizes', 'GABRIEL BARBOZA GOMES', 'EI - Mat. II'),
  ('Perdizes', 'GUILHERME XAVIER ALTMAN', 'EI - Mat. I'),
  ('Perdizes', 'HELENA LOURENÇO CASMALLA', 'EI - Mat. I'),
  ('Perdizes', 'HELENA MARTINS DENADAI', 'EI - Mat. I'),
  ('Perdizes', 'HENRIQUE LIBANORI ARRIGO', 'EI - Mat. I'),
  ('Perdizes', 'ISIS FERRARO BOHME', 'EI - Mat. I'),
  ('Perdizes', 'JOÃO FELIPE BRESSAN BERNINI', 'EI - Mat. I'),
  ('Perdizes', 'JOÃO PEDRO DE DEUS BASSAN', 'EI - Mat. I'),
  ('Perdizes', 'LUCAS BENETTI PORTO', 'EI - Mat. I'),
  ('Perdizes', 'LUCAS SCHIMIDT MINANNI', 'EI - Mat. I'),
  ('Perdizes', 'LUIZA FERREIRA GARCIA', 'EI - Mat. I'),
  ('Perdizes', 'MANUELA ZEZZI HABRUM', 'EI - Mat. II'),
  ('Perdizes', 'MARIA CLARA GUARDA CARDILLO BARBOSA BARAKAT', 'EI - Mat. I'),
  ('Perdizes', 'MARTIN CHAGAS BOAVENTURA', 'EI - Mat. I'),
  ('Perdizes', 'MATHEUS BISCARO FONSECA', 'EI - Mat. I'),
  ('Perdizes', 'MATHEUS SCHIMIDT MINANNI', 'EI - Mat. I'),
  ('Perdizes', 'MATTEO MARASCA', 'EI - Mat. I'),
  ('Perdizes', 'NICO MICHELLE MURAYAMA IEFFA', 'EI - Mat. I'),
  ('Perdizes', 'NINA OLIVEIRA FERRAZ', 'EI - Mat. I'),
  ('Perdizes', 'OLIVIA SOUZA LINO', 'EI - Mat. I'),
  ('Perdizes', 'RAFAEL COELHO GASPAR PINI', 'EI - Mat. I'),
  ('Perdizes', 'RAFAEL SILVEIRA DE LUCA', 'EI - Mini'),
  ('Perdizes', 'RAFAELA ARUZZO DOS RAMOS', 'EI - Mat. I'),
  ('Perdizes', 'SOPHIA GUAZZELLI MARASSI', 'EI - Mini'),
  ('Perdizes', 'STELLA CASTRO FIGUEIREDO', 'EI - Mat. I'),
  ('Perdizes', 'Verena Quirino Graglia', 'EI - Mat. I'),
  ('Klabin', 'CELINA SOUZA FILGUEIRAS RIBEIRO', 'EI - Berçário'),
  ('Klabin', 'JULIA GONDO MAZALI', 'EI - Berçário'),
  ('Klabin', 'LAURA ARNÁ HOLZER', 'EI - Berçário'),
  ('Klabin', 'THEO NOGUEIRA SILVÉRIO', 'EI - Berçário'),
  ('Klabin', 'BEATRIZ MORAIS AZEVEDO', 'EI- Mini maternal'),
  ('Klabin', 'BELLA BARROS DE MATTOS POSTAL', 'EI- Mini maternal'),
  ('Klabin', 'BENJAMIN MOREIRA BORGES DE CARVALHO', 'EI- Mini maternal'),
  ('Klabin', 'DANIEL NOGUEIRA SOARES E SILVA', 'EI- Mini maternal'),
  ('Klabin', 'DANIELA GIUSTO MACIERI', 'EI- Mini maternal'),
  ('Klabin', 'DOMENICA CHAGAS ZEPPELINI', 'EI- Mini maternal'),
  ('Klabin', 'GUSTAVO GUASTI RSTOM', 'EI- Mini maternal'),
  ('Klabin', 'KATARA UEDA SATAKE', 'EI- Mini maternal'),
  ('Klabin', 'LARA ANDRADE REGIS', 'EI- Mini maternal'),
  ('Klabin', 'MARIA TERESA LIMA CSAPO', 'EI- Mini maternal'),
  ('Klabin', 'GUILHERME OLIVEIRA ABREU', 'EI - Mat. I'),
  ('Klabin', 'ALVARO JOSÉ MONTEIRO DE ARAÚJO CAPELASSO', 'EI - Mat. I'),
  ('Klabin', 'ANTHONY LEANDRO GONÇALVES MARGARITELLI', 'EI - Mat. I'),
  ('Klabin', 'ARTHUR DURAN GARCIA', 'EI - Mat. I'),
  ('Klabin', 'BERNARDO HIRANO BRONZERI MORAES', 'EI - Mat. I'),
  ('Klabin', 'ESTHER LAN', 'EI - Mat. I'),
  ('Klabin', 'FELIPE CHAN DE BENEDETTE', 'EI - Mat. I'),
  ('Klabin', 'HÉLOÏSE CASTRO FLEURIMONT', 'EI - Mat. I'),
  ('Klabin', 'ISADORA SAORI MATSUMOTO QUARESMA', 'EI - Mat. I'),
  ('Klabin', 'LÍVIA PEREIRA DE SOUSA AULICINO', 'EI - Mat. I'),
  ('Klabin', 'MAITÊ DE OLIVEIRA HASS', 'EI - Mat. I'),
  ('Klabin', 'MANUELA CAMPOS SAMPAIO', 'EI - Mat. I'),
  ('Klabin', 'MARIANA ABIBI ANDRADE', 'EI - Mat. I'),
  ('Klabin', 'MATTEO GUEDES GATTI', 'EI - Mat. I'),
  ('Klabin', 'MIGUEL ARIKA GOMES SAMOS', 'EI - Mat. I'),
  ('Klabin', 'NAOMI ABBAS KAYANO', 'EI - Mat. I'),
  ('Klabin', 'VICTOR SALGADO ALVARES LEITE', 'EI - Mat. I'),
  ('Klabin', 'VINÍCIUS SALGADO ÁLVARES LEITE', 'EI - Mat. I'),
  ('Klabin', 'YOHAN ZHIHENG DOREA LEI', 'EI - Mat. I'),
  ('Klabin', 'ANA LUÍSA NOGUEIRA MOUAOUAD', 'EI - Mat. II'),
  ('Klabin', 'ANTONELLA AKEMI ZAGORDO NIKAIDO', 'EI - Mat. II'),
  ('Klabin', 'BEATRIZ LACANNA GOITIA', 'EI - Mat. II'),
  ('Klabin', 'BERNARDO CUTRUPI MELINAS CELANDRONI', 'EI - Mat. II'),
  ('Klabin', 'CAROLINA BURCKART DE MATTOS', 'EI - Mat. II'),
  ('Klabin', 'CLARA GIUSTO MACIERI', 'EI - Mat. II'),
  ('Klabin', 'CLARA PRATA ZANCOPE', 'EI - Mat. II'),
  ('Klabin', 'GABRIEL PICCOLI NEDELTSEF', 'EI - Mat. II'),
  ('Klabin', 'GUILHERME DOS SANTOS CARVALHO DOURADO', 'EI - Mat. II'),
  ('Klabin', 'GUSTAVO HENRIQUE HIGA CUGINOTTI', 'EI - Mat. II'),
  ('Klabin', 'HELENA CARVALHO BINI', 'EI - Mat. II'),
  ('Klabin', 'HENRIQUE CAMARGO QUEIROZ', 'EI - Mat. II'),
  ('Klabin', 'ISABELLI STORELLI CONSANI ROSA', 'EI - Mat. II'),
  ('Klabin', 'JOÃO HENRIQUE ALMEIDA BERALDI MAMEDE', 'EI - Mat. II'),
  ('Klabin', 'JOAQUIM HEREDIA SANTOS', 'EI - Mat. II'),
  ('Klabin', 'JOAQUIM OLIVEIRA SOUZA', 'EI - Mat. II'),
  ('Klabin', 'KAZUO UEDA SATAKE', 'EI - Mat. II'),
  ('Klabin', 'LEONARDO GIORGETTI AMADIO', 'EI - Mat. II'),
  ('Klabin', 'LEONARDO ROCHA DURAN', 'EI - Mat. II'),
  ('Klabin', 'LORENA DI POLITO MACHADO DE LORENZI', 'EI - Mat. II'),
  ('Klabin', 'LUCAS MILANO OHASHI', 'EI - Mat. II'),
  ('Klabin', 'LUCCA LUCIDONIO LIGABUE', 'EI - Mat. II'),
  ('Klabin', 'LUIZA MIYUKI SAMOS DE MENESES', 'EI - Mat. II'),
  ('Klabin', 'MAITÊ BONI ARENELLA', 'EI - Mat. II'),
  ('Klabin', 'MARIA ISADORA GIOVANETTI REZEK', 'EI - Mat. II'),
  ('Klabin', 'MARINA PIRES PIMENTEL', 'EI - Mat. II'),
  ('Klabin', 'MELISSA DE SOUZA BRANDÃO', 'EI - Mat. II'),
  ('Klabin', 'MICHAEL BENJAMIN CHEN CABELLO', 'EI - Mat. II'),
  ('Klabin', 'NAOMI ARAKI TRAVASSOS', 'EI - Mat. II'),
  ('Klabin', 'NATHAN CASTRO FLEURIMONT', 'EI - Mat. II'),
  ('Klabin', 'NATHAN RIVIERE TOUTE PADILHA', 'EI - Mat. II'),
  ('Klabin', 'OLIVIA SERRA CAVALHEIRI', 'EI - Mat. II'),
  ('Klabin', 'OSCAR EDUARDO HINOJOSA PUMA', 'EI - Mat. II'),
  ('Klabin', 'PEDRO ZANUCCELLI ROCHA ESPÍNDOLA', 'EI - Mat. II'),
  ('Klabin', 'SOFIA ANTONELLA HINOJOSA PUMA', 'EI - Mat. II'),
  ('Klabin', 'ALICE ALMEIDA PASQUINI', 'EI - Jardim'),
  ('Klabin', 'ANTONIO LIMA BARBAROTO', 'EI - Jardim'),
  ('Klabin', 'BENÍCIO IBARRA LOPEZ', 'EI - Jardim'),
  ('Klabin', 'BENJAMIN RAMOS BIANCO', 'EI - Jardim'),
  ('Klabin', 'CECÍLIA DE ALMEIDA BERALDI', 'EI - Jardim'),
  ('Klabin', 'CECILIA MATHIAS LUZ', 'EI - Jardim'),
  ('Klabin', 'DAVI MARUCCI SOARES', 'EI - Jardim'),
  ('Klabin', 'LIA SANTACHIARA DE VASCONCELOS SANTOS', 'EI - Jardim'),
  ('Klabin', 'LORENZO RIZZATTI LARDELLI', 'EI - Jardim'),
  ('Klabin', 'LUISA BOARI ELIAS', 'EI - Jardim'),
  ('Klabin', 'LUISA LIMA CSAPO', 'EI - Jardim'),
  ('Klabin', 'LUÍSA OLIVEIRA ABREU', 'EI - Jardim'),
  ('Klabin', 'MANUELA NUNES SANCHES', 'EI - Jardim'),
  ('Klabin', 'MARINA PEÇANHA CAMARGO', 'EI - Jardim'),
  ('Klabin', 'MATHEUS DE OLIVEIRA PEREIRA', 'EI - Jardim'),
  ('Klabin', 'PEDRO SARAIVA HANATO', 'EI - Jardim'),
  ('Klabin', 'RAFAEL CHAN DE BENEDETTE', 'EI - Jardim'),
  ('Klabin', 'UMBERTO DE MORAES FORJAZ BASTIGLIA', 'EI - Jardim'),
  ('Klabin', 'VITOR BARBOSA VEIGA', 'EI - Jardim'),
  ('Klabin', 'ALICE LACERDA GOTO', 'EI - Pré'),
  ('Klabin', 'ANNE HARADA DE CARVALHO', 'EI - Pré'),
  ('Klabin', 'ARTHUR LEANDRO GONÇALVES MARGARITELLI', 'EI - Pré'),
  ('Klabin', 'BELLA RODRIGUES DE CASTRO', 'EI - Pré'),
  ('Klabin', 'DOM LUCIDONIO LIGABUE', 'EI - Pré'),
  ('Klabin', 'HEITOR RIBEIRO COSENZA', 'EI - Pré'),
  ('Klabin', 'JASMINE GASPAR VIANA DE CASTRO', 'EI - Pré'),
  ('Klabin', 'JOAO VICTOR HIGA CUGINOTTI', 'EI - Pré'),
  ('Klabin', 'JOHAN JOSÉ DE OLIVEIRA HASS', 'EI - Pré'),
  ('Klabin', 'JULIA CAMARGO LEMOS', 'EI - Pré'),
  ('Klabin', 'LANA HEE TAE', 'EI - Pré'),
  ('Klabin', 'MARIANE LACERDA GOTO', 'EI - Pré'),
  ('Klabin', 'OLÍVIA CERRÓN BASSAN', 'EI - Pré'),
  ('Klabin', 'SARAH NATSUMI BEZERRA HISAMOTO', 'EI - Pré'),
  ('Real Parque', 'Antônio Fernando Welsel Mazaia', 'EI - Berçário'),
  ('Real Parque', 'Bento Santini Pozzani', 'EI - Berçário'),
  ('Real Parque', 'Catarina Mahnke Ferreira', 'EI - Berçário'),
  ('Real Parque', 'Elis Carvalho Veronese', 'EI - Berçário'),
  ('Real Parque', 'Helena Vieira Machado Buono', 'EI - Berçário'),
  ('Real Parque', 'Manuela Rossi Mezei', 'EI - Berçário'),
  ('Real Parque', 'MANUELLA MAGALHÃES PIANCA', 'EI - Berçário'),
  ('Real Parque', 'MARC GUILHERME MANCINI', 'EI - Berçário'),
  ('Real Parque', 'Matheus Ulhôa Rodrigues Sedrim Alves', 'EI - Berçário'),
  ('Real Parque', 'Alice Afonso Moraes', 'EI - Jardim'),
  ('Real Parque', 'Anne Catherine Barbosa Hayashida', 'EI - Jardim'),
  ('Real Parque', 'ANTONELLA TOMAZ CARFI', 'EI - Jardim'),
  ('Real Parque', 'Bento Borges de Oliveira', 'EI - Jardim'),
  ('Real Parque', 'Bernardo Venâncio Casale', 'EI - Jardim'),
  ('Real Parque', 'Gabriel de Almeida Braga Franco', 'EI - Jardim'),
  ('Real Parque', 'Gabriel Nobile Christofi', 'EI - Jardim'),
  ('Real Parque', 'Gregor Turella Szoke Medeiros Carneiro', 'EI - Jardim'),
  ('Real Parque', 'Luísa Verissimo Brito', 'EI - Jardim'),
  ('Real Parque', 'Marcela Rapino Lemes', 'EI - Jardim'),
  ('Real Parque', 'Maria Hernandes Pinheiro', 'EI - Jardim'),
  ('Real Parque', 'Maria Luiza Carneiro Cerqueira Machado', 'EI - Jardim'),
  ('Real Parque', 'Marina Rapino Lemos', 'EI - Jardim'),
  ('Real Parque', 'MATHEUS LIMA BIZARRO da Rocha', 'EI - Jardim'),
  ('Real Parque', 'Matteo Wanner Cervantes', 'EI - Jardim'),
  ('Real Parque', 'Murilo Castilho Satlher', 'EI - Jardim'),
  ('Real Parque', 'Romeu Dal Bello Nersessian', 'EI - Jardim'),
  ('Real Parque', 'Arthur Nogueira Frias', 'EI - Mat. I'),
  ('Real Parque', 'Benício Albano Mello Almeida', 'EI - Mat. I'),
  ('Real Parque', 'Caio Mansur de Azevedo Sodré', 'EI - Mat. I'),
  ('Real Parque', 'Cecília Verissimo Brito', 'EI - Mat. I'),
  ('Real Parque', 'Chloe Furbino Linemburg', 'EI - Mat. I'),
  ('Real Parque', 'Dom Carvalho de Freitas', 'EI - Mat. I'),
  ('Real Parque', 'Gabriel Duarte Mendes Teixeira', 'EI - Mat. I'),
  ('Real Parque', 'Gael Noschang Coelho Nagel', 'EI - Mat. I'),
  ('Real Parque', 'Isabel Tavoloni de Almeida', 'EI - Mat. I'),
  ('Real Parque', 'Luigi Storini Tecco', 'EI - Mat. I'),
  ('Real Parque', 'MARIA FERNANDA MONTEIRO DA SILVA', 'EI - Mat. I'),
  ('Real Parque', 'Martina Grassone Trigo', 'EI - Mat. I'),
  ('Real Parque', 'Sienna Vilatoro Nardi', 'EI - Mat. I'),
  ('Real Parque', 'Théo de Freitas Silva', 'EI - Mat. I'),
  ('Real Parque', 'Antonio Hernandes Britto', 'EI - Mat. II'),
  ('Real Parque', 'Arthur Henrique Seara Despinoy', 'EI - Mat. II'),
  ('Real Parque', 'Becca Sobreira de Almeida', 'EI - Mat. II'),
  ('Real Parque', 'Bella de Andrade Marques Erbolato', 'EI - Mat. II'),
  ('Real Parque', 'Cecília Caruso Blanco', 'EI - Mat. II'),
  ('Real Parque', 'Eduardo Izidoro Pace', 'EI - Mat. II'),
  ('Real Parque', 'Eduardo Rocha Rebane Santos', 'EI - Mat. II'),
  ('Real Parque', 'ENRICO DE LACERDA LOPES', 'EI - Mat. II'),
  ('Real Parque', 'ESTHER BARBOSA DE BARROS', 'EI - Mat. II'),
  ('Real Parque', 'Gabriel de Almeida Fernandes', 'EI - Mat. II'),
  ('Real Parque', 'Isabella Magalhães Pianca', 'EI - Mat. II'),
  ('Real Parque', 'João Pedro Souto Maior', 'EI - Mat. II'),
  ('Real Parque', 'Lígia Mazaia Welsel', 'EI - Mat. II'),
  ('Real Parque', 'Lorenzo de Abreu Sampaio Musa', 'EI - Mat. II'),
  ('Real Parque', 'Lucca Janaudis Dias', 'EI - Mat. II'),
  ('Real Parque', 'Manuela Fernandes Felipe', 'EI - Mat. II'),
  ('Real Parque', 'MARIA CLARA NOGUEIRA GALVÃO LEMOS', 'EI - Mat. II'),
  ('Real Parque', 'Maria Julia Pires Paiva', 'EI - Mat. II'),
  ('Real Parque', 'Maya Ferreira', 'EI - Mat. II'),
  ('Real Parque', 'Nicolas Miguel Paduan', 'EI - Mat. II'),
  ('Real Parque', 'Olamiposi Miguel Aqsad Saibu', 'EI - Mat. II'),
  ('Real Parque', 'Otávio Evangelista Bastos', 'EI - Mat. II'),
  ('Real Parque', 'PEDRO PERES PINTO', 'EI - Mat. II'),
  ('Real Parque', 'Rodrigo Albano Mello Almeida', 'EI - Mat. II'),
  ('Real Parque', 'THÉO ANDRADE DE OLIVEIRA MARTINS', 'EI - Mat. II'),
  ('Real Parque', 'Zoe Soares Santos', 'EI - Mat. II'),
  ('Real Parque', 'Alice Carceles Goldenberg', 'EI - Mini'),
  ('Real Parque', 'Beatriz Caleffi Mussatto', 'EI - Mini'),
  ('Real Parque', 'Daniel Sultani Rocha', 'EI - Mini'),
  ('Real Parque', 'Helena de Freitas Henrique Silva', 'EI - Mini'),
  ('Real Parque', 'João Caranassios Netto', 'EI - Mini'),
  ('Real Parque', 'Martin Zapata Fernandes', 'EI - Mini'),
  ('Real Parque', 'Matteo Fábrega Cardoso', 'EI - Mini'),
  ('Real Parque', 'Noah Martire Oliveira', 'EI - Mini'),
  ('Real Parque', 'Pietra Hernandes Pinheiro', 'EI - Mini'),
  ('Real Parque', 'Rafael Dib Pacheco', 'EI - Mini'),
  ('Real Parque', 'Henrique Castro Sachet', 'EI - Mini'),
  ('Real Parque', 'Isabela de Castro Merhy', 'EI - Mini'),
  ('Real Parque', 'Aya Pineschi dos Passos', 'EI - Pré'),
  ('Real Parque', 'Benicio Arcaro Teixeira', 'EI - Pré'),
  ('Real Parque', 'BENÍCIO GUARIENTO ORRÚ', 'EI - Pré'),
  ('Real Parque', 'CECÍLIA MARTIN QUEIROZ', 'EI - Pré'),
  ('Real Parque', 'Enrico Braz Santomartino', 'EI - Pré'),
  ('Real Parque', 'Francisco de Alcantara Manesco', 'EI - Pré'),
  ('Real Parque', 'Gustavo Maldonado Witte', 'EI - Pré'),
  ('Real Parque', 'Joaquim Melo Savaglia', 'EI - Pré'),
  ('Real Parque', 'Leonardo Rocha Rebone Santos', 'EI - Pré'),
  ('Real Parque', 'Lorenzo Diniz Leite', 'EI - Pré'),
  ('Real Parque', 'Mariane Rado Lima', 'EI - Pré'),
  ('Real Parque', 'Olívia May Caetano Corbett', 'EI - Pré'),
  ('Real Parque', 'Pedro Casali Castello Branco', 'EI - Pré'),
  ('Real Parque', 'Pedro Lucas de Melo Boulos', 'EI - Pré'),
  ('Real Parque', 'Theodora Targa Berlinck Diniz', 'EI - Pré')) AS v(unidade_nome, nome, turma) ON v.unidade_nome = p.unidade_nome
WHERE p.role = 'unidade'
  AND NOT EXISTS (
    SELECT 1 FROM public.rematricula_alunos r
    WHERE r.unidade_id = p.id AND r.nome = v.nome
  );
